### ISSUE TITLE
ASM end-user auth kpt instructions not working as expected

### ISSUE THREAD

**Issue by ilgatnau** [GoogleCloudPlatform/asm-user-auth#15]
kpt pkg get https://github.com/GoogleCloudPlatform/asm-user-auth@release-1.0 .

Package "asm-user-auth":
Fetching https://github.com/GoogleCloudPlatform/asm-user-auth@release-1.0
From https://github.com/GoogleCloudPlatform/asm-user-auth
 * branch            release-1.0 -> FETCH_HEAD
 * [new branch]      release-1.0 -> origin/release-1.0
Adding package "".
Error: Kptfile at "/tmp/kpt-get-059979794/pkg" has an old version ("v1alpha1") of the Kptfile schema.
Please update the package to the latest format by following https://kpt.dev/installation/migration

**Comment by ilgatnau** [comment]
kpt version
1.0.0-beta.4

**Comment by ilgatnau** [comment]
#14 will fix this, waiting for merge to test and close the issue

**Comment by liwenhao0810** [comment]
https://github.com/GoogleCloudPlatform/asm-user-auth/tree/release-1.0-kptv1 
The new release-1.0-kptv1 branch fixes this issue, please test on that branch and close this issue after.

**Comment by ilgatnau** [comment]
> kpt pkg get https://github.com/GoogleCloudPlatform/asm-user-auth@release-1.0-kptv1
Package "asm-user-auth":
Fetching https://github.com/GoogleCloudPlatform/asm-user-auth@release-1.0-kptv1
From https://github.com/GoogleCloudPlatform/asm-user-auth
 * branch            release-1.0-kptv1 -> FETCH_HEAD
 * [new branch]      release-1.0-kptv1 -> origin/release-1.0-kptv1
Adding package "".

Fetched 1 package(s).

---

Tested successfully, closing the issue
